flyway.user=${env:FLYWAY_USER}
flyway.password=${env:FLYWAY_PASSWORD}
flyway.schemas=public
flyway.url=${env:FLYWAY_URL}
flyway.locations=filesystem:src/main/resources/db/migration/postgresql
flyway.baselineOnMigrate = true