create table answer (id integer generated by default as identity, created_at timestamp(6), updated_at timestamp(6), answer_content varchar(255), question_id integer, primary key (id));
create table assessment (id integer generated by default as identity, created_at timestamp(6), updated_at timestamp(6), date_time_taken timestamp(6), feedback varchar(255), reviewing_counselor_id integer, student_id integer, primary key (id));
create table question (id integer generated by default as identity, created_at timestamp(6), updated_at timestamp(6), number integer, question_content varchar(2000), primary key (id));
alter table if exists answer add constraint FK8frr4bcabmmeyyu60qt7iiblo foreign key (question_id) references question;
