INSERT INTO Question (number, question_content) VALUES
(1, 'How often do you feel sad, down, or hopeless?'),
(2, 'Do you experience sudden mood swings or difficulty managing your emotions?'),
(3, 'How often do you feel overwhelmed or excessively stressed?'),
(4, 'Are you able to enjoy activities or hobbies that used to make you happy?'),
(5, 'Do you find it hard to concentrate or focus on tasks?'),
(6, 'Do you experience racing thoughts or excessive worry?'),
(7, 'Do you have frequent negative or self-critical thoughts?'),
(8, 'Have your eating or sleeping habits changed recently?'),
(9, 'Do you find it hard to stay motivated or complete daily tasks?'),
(10, 'Have you done things you regret, like drinking too much or using substances?'),
(11, 'Are you withdrawing from friends, family, or social activities?'),
(12, 'How often do you feel anxious or nervous in social or work situations?'),
(13, 'Are your relationships with family, friends, or coworkers fulfilling and supportive?'),
(14, 'Do you feel isolated or lonely most of the time?'),
(15, 'Do conflicts in relationships significantly affect your mood or stress levels?'),
(16, 'Do you often feel physically unwell without a clear medical reason?'),
(17, 'Do you feel confident in making decisions or facing challenges?'),
(18, 'Do you feel safe in your home, workplace, or other environments?'),
(19, 'Do you have clear goals or purpose in life that motivate you?'),
(20, 'Are you getting enough physical activity or exercise regularly?'),
(21, 'Are you engaging in risky behaviors that concern you or others?'),
(22, 'Have you considered seeking professional help for mental health concerns?'),
(23, 'Are you aware of resources like counseling or support groups nearby?'),
(24, 'Have you previously sought therapy, and was it beneficial for you?');